/* Generated by CoffeeScript 1.12.2
(function() {
  module.exports = function(robot) {
    var docsUrl, pagePrefix, referenceLink, sqlSuffix;
    docsUrl = 'http://www.w3schools.com/sql/';
    sqlSuffix = '.asp';
    pagePrefix = 'sql_';
    referenceLink = function(res) {
      var keywordName, ref, response;
      keywordName = (ref = res.match[1]) != null ? ref.replace(' ', '') : void 0;
      response = "Check out " + docsUrl + pagePrefix;
      response += keywordName;
      response += sqlSuffix;
      return res.send(response);
    };
    return robot.hear(/^!sql (\w*)/i, function(res) {
      return referenceLink(res);
    });
  };

}).call(this);
*/
